language: rust
env:
  - RUSTFLAGS="-D warnings"
script:
  - cargo build --verbose --all
  - cargo test --verbose --all

matrix:
  include:
    - rust: beta
    - rust: nightly-2018-08-24
    - rust: nightly-2018-08-24
      before_script:
        - rustup component add rustfmt-preview --toolchain nightly
      script:
        - cargo +nightly fmt --all -- --check
    - rust: stable
