[package]
name = "git-relative-status"
version = "0.1.0"
authors = ["Keith Smiley <keithbsmiley@gmail.com>"]

[dependencies]
# this crate copied a relative path implementation from rustc
pathdiff = "0.1.0"
